### ISSUE TITLE
how to modify the paths

### ISSUE THREAD

**Issue by FYYLHH** [s-duuu/pred_fusion#5]
Hello, I have trained the new YOLOv5 weights (V6.0 version) and the weights of pointpigs. May I know how to modify the paths of these two weights? Can you provide me with a detailed explanation? Thank you very much.
Looking forward to your reply

**Comment by s-duuu** [comment]
You can modify the paths of weight files in `integrated.launch` file. Most of the important arguments are defined there.

Thanks.

**Comment by FYYLHH** [comment]
I modified the weight yolo. pt of YOLO in line 4 of the launch file to the weight I trained, and the following error occurred: upsample "object has no attribute" recompute_ Scale_ What is this problem and how to solve it? Thank you




---Original---
From: "Kim ***@***.***&gt;
Date: Wed, Aug 23, 2023 15:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [s-duuu/pred_fusion] how to modify the paths (Issue #5)




 
You can modify the paths of weight files in integrated.launch file. Most of the important arguments are defined there.
 
Thanks.

**Comment by s-duuu** [comment]
Is your YOLO model version YOLOv5?

**Comment by FYYLHH** [comment]
yes，I am sure I am using YOLOv5, but it should be the weight obtained from YOLOv5's 6.0 training. After making changes, an error will be reported



---Original---
From: "Kim ***@***.***&gt;
Date: Wed, Aug 23, 2023 15:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [s-duuu/pred_fusion] how to modify the paths (Issue #5)




 
Is your YOLO model version YOLOv5?

**Comment by s-duuu** [comment]
It might be the problem with torch, so please refer to the following URL. It deals with the same issue you mentioned. 

https://github.com/ultralytics/yolov5/issues/6948

Thanks.

**Comment by FYYLHH** [comment]
Your response helped me solve the problem of Pillars not displaying detection boxes, but when I modified the weights of YOLOv5 and Pillars, I reported an error.
Yolo error:
RuntimeError: [force fail at inline container. cc: 130]. file in archive is not in a subdirectory: pillars.pth
/Opt/ros/noetic/lib/python3/dist packages/rose/impl/registration. py: 339: DeprecationWarning: notifyAll() is deprecated, use notify_ All() install
Self. nd. notifyAll()
Pillars error:
File "/home/fyy/yolo_point_fusion/dev/lib/usage reduction/detector. py", line 15, in<module>
Exec (compile (fh. read()), Python_ Script, 'exec'), context)
File "/home/fyy/yolo_point_fusion/src/src/detector. py", line 199, in<module>
Detector=Yolov5Detector()
File "/home/fyy/anaconde3/lib/python3.10/site packages/torch/utils/contextlib. py", line 115, in decorate_ Context
Return func (* args, * * kwargs)
File "/home/fyy/anaconde3/lib/python3.10/site packages/torch/utils/contextlib. py", line 129, in<lambda>
Func=cast (F, lambda * args, * * kwargs: orig_func (* args, * * kwargs))
File "/home/fyy/yolo_point_fusion/src/src/detector. py", line 77, in__ Init__
Self. model. warmup (imgsz=(1 if self. pt else bs, 3, * self. img_size), half=self. half) # warmup
File "/home/fyy/yolo_point_fusion/dev/lib/usage reduction/yolov5/models/common. py", line 463, in warmup
Self. forward (im) # warmup
File "/home/fyy/yolo_point_fusion/dev/lib/usage reduction/yolov5/models/common. py", line 402, in forward
Y=self. model (im) if self. jit else self. model (im, augment=augment, visualize=visualize)
File "/home/fyy/anaconde3/lib/python3.10/site packages/torch/nn/modules/module. py", line 1501, in_ Call_ Impl
Return forward_ Call (* args, * * kwargs)
File "/home/fyy/yolo_point_fusion/src/src/yolov5/models/yolo. py", line 209, in forward
Return self_ Forward_ Once (x, profile, visualize) # single scale conference, train
File "/home/fyy/yolo_point_fusion/src/src/yolov5/models/yolo. py", line 121, in_ Forward_ Once
X=m (x) # run
File "/home/fyy/anaconde3/lib/python3.10/site packages/torch/nn/modules/module. py", line 1501, in_ Call_ Impl
Return forward_ Call (* args, * * kwargs)
File "/home/fyy/anaconde3/lib/python3.10/site packages/torch/nn/modules/upsampling. py", line 157, in forward
Recompute_ Scale_ Factor=self. calculate_ Scale_ Factor)
File "/home/fyy/anaconde3/lib/python3.10/site packages/torch/nn/modules/module. py", line 1614, in__ Getattr__
Raise AttributeError ("{} 'object has no attribute' {} '". format（
AttributeError: 'Upsample' object has no attribute 'recompute_ Scale_ Factor '
[detector-2] process has died [pid 13758, exit code 1, cmd/home/fyy/yolo_point_fusion/dev/lib/usion_prediction/detector. py __ name:=detector__ log:=/home/fyy/. ros/log/13c5b734-421d-11ee beac-2b3c2abce79f/detector-2. log]
Log file:/home/fyy/. ros/log/13c5b734-421d-11ee beac-2b3c2abce79f/detector-2 *. log
/Opt/ros/noetic/lib/python3/dist packages/rose/impl/registration. py: 486: DeprecationWarning: notifyAll() is deprecated, use notify_ All() install
Self. nd. notifyAll()
/Home/fyy/anaconde3/lib/Python 3.10/site packages/torch/functional. py: 504: UserWarning: torch. meshgrid: in an updating release, it will be required to pass the indexing argument (Triggered internally at../ten/src/Aten/native/TensorShape. cpp: 3483.)
Return_ VF. meshgrid (tensors, * * kwargs) # type: ignore [attr defined]
[ERROR] [1692840322.884283]: bad callback:<bound method fusion. lidar_ Callback of<__ Main__ Fusion object at 0x7f8b769a9750>>
Traceback (most recent call last):
If it's convenient, could you help me see how this path problem arises and how it is resolved. thanks
Note: I noticed that you were originally in the zip format of the compressed package, but what I trained was not in the zip format. I suspect there may be a problem with this area. I tried to compress the weight and still reported an error, so I think you may have done additional work to ensure that the project runs correctly.
I hope to receive your early reply.

**Comment by s-duuu** [comment]
Sorry for late reply. Could you please summarize the key points of your error code?

Thanks.
